### ISSUE TITLE
mcDispatch(...) -> invalid source-mesh connectivity

### ISSUE THREAD

**Issue by AndreAhmed** [cutdigital/mcut#12]
Hello,
I'm trying the example of CSG boolean operation on a large scale skull mesh. and It fails..
I would like to purchase a commercial license, but I would like to use it on large scale meshes..
Can you show an example with Cutting a plane with that mesh and also extracting some parts of mesh to mesh intersection ?
Can you also provide an example plane cut with that mesh ?
[untitled.zip](https://github.com/cutdigital/mcut/files/10040648/untitled.zip)

**Comment by AndreAhmed** [comment]
Let me be more specific, for example I have the following laso, is it possible with a mesh like the following to extract the patch done by lasso ?
![image](https://user-images.githubusercontent.com/440842/202712833-6b34cb10-0e89-4efb-869b-7772f01ef5d3.png)

**Comment by chitalu** [comment]
Hi @AndreAhmed 

Thanks for using MCUT.

How exactly does it fail? An error message would be helpful. 

If the error message is "[mcDispatch(...) -> invalid source-mesh connectivity" as the title indicates, then it is because your source mesh (which is likely the skull mesh) has more than one connected component. MCUT expects that each input mesh is a single connected component. 

I have gone ahead anyway and separated the skull into its connected components to then cut cranium with a plane. The results are provided [here](https://drive.google.com/file/d/1ZQGNt5-DUStJn1-WFojhPy8JZn0Dz_Pe/view?usp=share_link)  for your reference (too large for attaching). These were produced with the BasicCmdLineApp tutorial code. 

An explanation of how to filter the output connected components computed by MCUT can be found [here](https://cutdigital.github.io/mcut.site/tutorials/helloWorld/) (see results section). The [CSGBoolean](https://github.com/cutdigital/mcut/tree/master/tutorials/CSGBoolean) tutorial also shows how to pass parameters to the dispatch function to tell MCUT how to compute your desired boolean operation. A more detailed example on how MCUT interprete's input meshes can also be found in the response to #8 . 

To get the contour points (i.e. vertices along the cut-path), you can use the following when querying connected component data:

```
size_t num_bytes =0;
McResult err = mcGetConnectedComponentData(context, conn_comp_id, MC_CONNECTED_COMPONENT_DATA_SEAM_VERTEX, 0, NULL, &num_bytes);
if(err != MC_NO_ERROR)
{
// do stuff..
}
std::vector<uint32_t> seam_vertices(num_bytes / sizeof(uint32_t), 0);
err = mcGetConnectedComponentData(context, conn_comp_id, MC_CONNECTED_COMPONENT_DATA_SEAM_VERTEX, num_bytes, &seam_vertices[0], NULL);
if(err != MC_NO_ERROR)
{
// do stuff..
}
```
`seam_vertices` will contain indices of the vertices of a connected component that are along the contour.

Finally, I have also generated a boolean operation result with the CSGBoolean tutorial code, whose results are also attached (see file "AndreAhmed-cube-boolean.zip").
[AndreAhmed-cube-boolean.zip](https://github.com/cutdigital/mcut/files/10042471/AndreAhmed-cube-boolean.zip)

For licensing details, you are welcome to send me an [email](floyd.m.chitalu@gmail.com).

![image](https://user-images.githubusercontent.com/7461679/202739329-e265f7bf-8c26-41b3-9af2-f647b57c8bbe.png)

**Comment by AndreAhmed** [comment]
@chitalu 
Thanks so much.
Do you have the example file above ?
I would like to see a demo also of curve that cuts the mesh into a patch, if that's possible with your library, because I have seen a comment in the github that it can do that

**Comment by chitalu** [comment]
If you are referring to the image, then the file can be found in the zip file called "[AndreAhmed-cube-boolean.zip](https://github.com/cutdigital/mcut/files/10042471/AndreAhmed-cube-boolean.zip)". Which I have referred to above as well.

Otherwise, I'm afraid I do not understand what you are referring to. It might help to be a bit more precise with what you need.

**Comment by AndreAhmed** [comment]
@chitalu 
Thanks for your fast response. 
I can't reproduce the results that you got, so can you please upload the modified HelloWolrd and BasicCmdLine files?
second issue:
1. I would like to cut the cranium with a curve, is that possible ? possible an spline,..etc of curves ?
