### ISSUE TITLE
Interpreting the seam results

### ISSUE THREAD

**Issue by lvjonok** [cutdigital/mcut#34]
Hello! I am trying to do seam query from cut mesh result and interpret the results

Gratefully, there is an [example](https://github.com/cutdigital/mcut/blob/master/tutorials/QuerySeamVerticesSorted/QuerySeamVerticesSorted.cpp) from your tutorials. I have a question whether in output the seam polygon preserves its winding order? Meaning, can I understand by the order of vertices whether the path is a hole or a solid one?

**Comment by chitalu** [comment]
Hi @lvjonok 

Can you provide a visual illustration with your question? Its a little ambiguious for me to answer correctly. 

(its also unclear what is meant by a path that is 'a hole or a solid one')

**Comment by lvjonok** [comment]
Okay, so

I have such model ![image](https://github.com/cutdigital/mcut/assets/42120385/a2f8a719-1d09-4107-bc86-1a1932e962cf) and want to slice it with a plane mesh. As result I get such seam: 
![image](https://github.com/cutdigital/mcut/assets/42120385/f3828ec1-9a32-4e9d-8788-5125f451fedf)

The mesh I slice with is the following:

```
OFF
4 2 0
656.017504 754.745675 0.199722
754.745675 -656.017504 0.199722
-656.017504 -754.745675 0.199722
-754.745675 656.017504 0.199722
3 0 1 2 
3 0 2 3 
```

I expected that inner and outer paths would have same winding direction, but it is different in the result.
A path being a hole or a solid by its winding direction. A hole will have clock-wise winding, a solid path is opposite.

**Comment by chitalu** [comment]
I see now. Thanks. 

>> whether in output the seam polygon preserves its winding order?

... Then the simple answer is unfortunately no. But there are workarounds.

The detailed answer is that it is not possible to preserve winding order between multiple 'seam polygons' because MCUT determines the sequential order of each such polygon by _only_ using the topology/halfedge-connectivity of a connected component. 

A potential workaround would enforce 'winding direction' (i.e. reversing the output sequences(s) to match your desired winding order) by resorting to calculations that involve the geometry/vertices of the polygon(s). This could be with the [orient2d](https://www.cs.cmu.edu/~quake/robust.html) predicate or the [winding number](https://igl.ethz.ch/projects/winding-number/), if your seam polygon is always produced by slicing the source-mesh with a planar mesh (to guarrantee planar output seam polygons).

**Comment by lvjonok** [comment]
Fine, thank you!

I think I will infer the direction of paths from faces of result.
