### ISSUE TITLE
SEALING FRAGMENT missing faces

### ISSUE THREAD

**Issue by Yourbee** [cutdigital/mcut#36]
![image](https://github.com/cutdigital/mcut/assets/10266225/67e33dda-275d-45b6-80fd-c168aea9b84c)

![image](https://github.com/cutdigital/mcut/assets/10266225/6f06a87a-c944-4deb-b5d1-54c393e7660b)

https://drive.google.com/drive/folders/1CJBihfQMN4d1W9-JELtoK52jQ6msenDr?usp=drive_link

**Comment by Yourbee** [comment]
when this happened, MC_DISPATCH_FILTER_FRAGMENT_LOCATION_ABOVE | MC_DISPATCH_FILTER_FRAGMENT_SEALING_OUTSIDE get the SEALING FRAGMENT inside. 

Normally MC_DISPATCH_FILTER_FRAGMENT_LOCATION_ABOVE | MC_DISPATCH_FILTER_FRAGMENT_SEALING_INSIDE get get the SEALING FRAGMENT inside

**Comment by chitalu** [comment]
Hi @Yourbee,

The file(s) cannot be accessed without permission. A publicly accessible link is required.

Alternatively, you may attached the file(s) here if it is small enough.

**Comment by Yourbee** [comment]
> Hi @Yourbee,
> 
> The file(s) cannot be accessed without permission. A publicly accessible link is required.
> 
> Alternatively, you may attached the file(s) here if it is small enough.

OK, the file zip is here
[mcut test data.zip](https://github.com/cutdigital/mcut/files/13751740/mcut.test.data.zip)

**Comment by chitalu** [comment]
Hi @Yourbee 

The problem is due to the fact that your input mesh "solid.obj" has faces with a reversed winding order (CW instead of CCW). That is your faces indices are reversed. This is probably because "solid.obj" was an output fragment of a preceeding mcDispatch call. 

Fragments that are "below" and sealed from the "outside" shall always have a reversed winding order w.r.t the input source-mesh. Refer to #8 for a gist on how MCUT computes the output.
And then refer to [this](https://github.com/cutdigital/mcut/tree/master/tutorials/ReversedConnectedComponentFaces) tutorial on how to request face indices with reversed winding order for such fragments.

That should address your problem. 

For reference here is your original mesh (view in MeshLab)
![image](https://github.com/cutdigital/mcut/assets/7461679/735ad30c-f306-49d9-8318-db275135ab24)

And here is the one after flipping the winding order (i.e. reversing the normals)
![image](https://github.com/cutdigital/mcut/assets/7461679/19d29787-1317-42e7-a919-9154d08e2114)
